import { WebsiteRoutePath } from '../shared/modules/website'


export const ADMIN_ROUTE_PATH = `${WebsiteRoutePath}/admin`
export const ADMIN_ROUTE_NAME = 'ADMIN'

export const ADMIN_BASE_MASTER = "ADMIN@LAYOUT_MASTER"

export const MENU_HEADER = 'ADMIN@MENU_HEADER'

//# CONSTRUCTION
export const CONSTRUCTION_MASTER = "ADMIN@CONSTRUCTION_LAYOUT_MASTER"
export const CONSTRUCTION_MENU_SIDER = 'ADMIN@CONSTRUCTION_MENU_SIDER'
export const CONSTRUCTION = 'ADMIN@ROUTE_CONSTRUCTION'
export const CONSTRUCTION_INDEX = 'ADMIN@CONSTRUCTION_INDEX'
export const CONSTRUCTION_NEW = 'ADMIN@ROUTE_CONSTRUCTION_NEW'
export const CONSTRUCTION_UPDATE = 'ADMIN@ROUTE_CONSTRUCTION_UPDATE'